packages:
  - playground
  - docs
  - packages/*
  - examples/*

configDependencies:
  '@pnpm/plugin-trusted-deps': 0.2.1+sha512-eexZgdsCkalvvWOdtlhlLoMg5Kylqj7CjeAzhSshEi3Io3TJawdKNwRg10ObK0V4DSWNF0lP2ilobwUKUdoCyw==

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lefthook
